INSERT INTO blogful_articles (title, content, date_published)
VALUES
  ('We''re Thundercats, Ho', 'Thundercats are on the move, Thundercats are loose. Feel the magic, hear the roar, Thundercats are loose. Thunder, thunder, thunder, Thundercats! Thunder, thunder, thunder, Thundercats! Thunder, thunder, thunder, Thundercats! Thunder, thunder, thunder, Thundercats! Thundercats!', now() - '20 days'::INTERVAL),
  ('Barnaby the Bear', 'Barnaby The Bear''s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear''s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you''d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.', now() - '19 days'::INTERVAL),
  ('MURDER!', 'This is my boss, Jonathan Hart, a self-made millionaire, he''s quite a guy. This is Mrs H., she''s gorgeous, she''s one lady who knows how to take care of herself. By the way, my name is Max. I take care of both of them, which ain''t easy, ''cause when they met it was MURDER!', now() - '18 days'::INTERVAL),
  ('Knight Rider', 'Knight Rider, a shadowy flight into the dangerous world of a man who does not exist. Michael Knight, a young loner on a crusade to champion the cause of the innocent, the helpless in a world of criminals who operate above the law.', now() - '17 days'::INTERVAL),
  ('Muskehounds', 'One for all and all for one, Muskehounds are always ready. One for all and all for one, helping everybody. One for all and all for one, it’s a pretty story. Sharing everything with fun, that''s the way to be. One for all and all for one, Muskehounds are always ready. One for all and all for one, helping everybody. One for all and all for one, can sound pretty corny. If you''ve got a problem chum, think how it could be.', now() - '16 days'::INTERVAL),
  ('Mutley', 'Mutley, you snickering, floppy eared hound. When courage is needed, you''re never around. Those medals you wear on your moth-eaten chest should be there for bungling at which you are best. So, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon. Howwww! Nab him, jab him, tab him, grab him, stop that pigeon now.', now() - '3 days'::INTERVAL),
  ('Hong Kong Phooey', 'Hong Kong Phooey, number one super guy. Hong Kong Phooey, quicker than the human eye. He''s got style, a groovy style, and a car that just won''t stop. When the going gets tough, he''s really rough, with a Hong Kong Phooey chop (Hi-Ya!). Hong Kong Phooey, number one super guy. Hong Kong Phooey, quicker than the human eye. Hong Kong Phooey, he''s fan-riffic!', now() - '15 days'::INTERVAL),
  ('Ulysses', 'Ulysses, Ulysses — Soaring through all the galaxies. In search of Earth, flying in to the night. Ulysses, Ulysses — Fighting evil and tyranny, with all his power, and with all of his might. Ulysses — no-one else can do the things you do. Ulysses — like a bolt of thunder from the blue. Ulysses — always fighting all the evil forces bringing peace and justice to all.', now() - '14 days'::INTERVAL),
  ('Moving on', 'There''s a voice that keeps on calling me. Down the road, that''s where I''ll always be. Every stop I make, I make a new friend. Can''t stay for long, just turn around and I''m gone again. Maybe tomorrow, I''ll want to settle down, Until tomorrow, I''ll just keep moving on.', now() - '4 days'::INTERVAL),
  ('Top Cat', 'Top Cat! The most effectual Top Cat! Who''s intellectual close friends get to call him T.C., providing it''s with dignity. Top Cat! The indisputable leader of the gang. He''s the boss, he''s a pip, he''s the championship. He''s the most tip top, Top Cat.', now() - '2 days'::INTERVAL),
  ('Stuntman Gigolo', 'I never spend much time in school but I taught ladies plenty. It''s true I hire my body out for pay, hey hey. I''ve gotten burned over Cheryl Tiegs, blown up for Raquel Welch. But when I end up in the hay it''s only hay, hey hey. I might jump an open drawbridge, or Tarzan from a vine. ''Cause I''m the unknown stuntman that makes Eastwood look so fine.', now() - '13 days'::INTERVAL),
  ('Sun Kids', 'Children of the sun, see your time has just begun, searching for your ways, through adventures every day. Every day and night, with the condor in flight, with all your friends in tow, you search for the Cities of Gold. Ah-ah-ah-ah-ah… wishing for The Cities of Gold. Ah-ah-ah-ah-ah… some day we will find The Cities of Gold. Do-do-do-do ah-ah-ah, do-do-do-do, Cities of Gold. Do-do-do-do, Cities of Gold. Ah-ah-ah-ah-ah… some day we will find The Cities of Gold.', now() - '12 days'::INTERVAL),
  ('Bear BJ', 'Hey there where ya goin'', not exactly knowin'', who says you have to call just one place home. He''s goin'' everywhere, B.J. McKay and his best friend Bear. He just keeps on movin'', ladies keep improvin'', every day is better than the last. New dreams and better scenes, and best of all I don’t pay property tax. Rollin'' down to Dallas, who''s providin'' my palace, off to New Orleans or who knows where. Places new and ladies, too, I''m B.J. McKay and this is my best friend Bear.', now() - '11 days'::INTERVAL),
  ('Around the World in 80 days','80 days around the world, we''ll find a pot of gold just sitting where the rainbow''s ending. Time — we''ll fight against the time, and we''ll fly on the white wings of the wind. 80 days around the world, no we won''t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.', now() - '10 days'::INTERVAL),
  ('Quarantini', 'Add 2 oz gin, .5 oz sweet vermouth, a dash of bitters, and your fucking tears of boredom and isolation into a shaker with ice. Shake vigorously and strain into a martini glass. Serve to yourself.', now() - '9 days'::INTERVAL),
  ('Jack', 'All work and no play make Jack a dull boy. All work and no play make Jack a dull boy. All work and no play make Jack a dull boy. All work and no play make Jack a dull boy. ALL WORK AND NO PLAY MAKE JACK A DULL BOY. ALL WORK AND NO PLAY MAKE JACK A DULL BOY. ALL WORK AND NO PLAY MAKE JACK A DULL BOY. ALL WORK AND NO PLAY MAKE JACK A DULL BOY.', now() - '8 days'::INTERVAL),
  ('This...', '...is getting tedious.', now() - '7 days'::INTERVAL),
  ('Title to be determined', 'Placeholder text', now() - '6 days'::INTERVAL),
  ('Lorem Dipshit', 'Lorem ipsum dolor sit amet, at insolens consulatu percipitur nam, cu aliquando interesset vix. Ea eos nulla aliquid ancillae, sit latine scaevola ocurreret an. Graeco nostrum salutandi ex per, et idque epicurei est. Numquam deleniti senserit ad eos, id altera oportere reprehendunt quo.', now() - '5 days'::INTERVAL),
  ('I''m done!', 'With all this stupid dummy data! I hope it works...', now() - '1 days'::INTERVAL)
;